### ISSUE TITLE
bad grouping 

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#19]
I really dont like this grouping, since it provides a overhead  just to group the mappings . 
I would like to have type = NONE as default i guess ?!
Or we just keep them single if they are not directly related (apart from having the same root)
  
```YAML
  - name: "body site"
    with:
      fhir: "$fhirRoot.bodySite"
      type: "NONE" 
    followedBy:
      mappings:
        - name: "body site code"
          with:
            fhir: "coding"
            openehr: "/data[at0001]/items[at0012]" # Body site
            type: "CODING"
.....
```
