### ISSUE TITLE
Add generic mapping to all model mapping files

### ISSUE THREAD

**Issue by gasperr** [medblocks/openFHIR#2]
Add the following to all model mapping files and don't forget to adjust the schema (else validation will fail). Schema changes will need to be aligned with FHIRConnect spec github repo maintainers.

```
environment:
   version: 0.0.1a # mapping version for track and history
   format:
     system: OMOCL # could be FHIRConnect
     version: v0.01 # e.g. R4
   target:
     system: FHIR
     version: R4

openEhrConfig:
   archetype: "openEHR-EHR-INSTRUCTION.medication_order.v2"
```

Current header as per spec looks like
Model:
```
format: "0.2.0"
version: "0.0.1"

fhirConfig:
  resource: "Condition"
  multiple: true
  condition:
    - targetRoot: "$fhirResource"
      targetAttribute: "extension.url"
      operator: "one of"
      criteria: "[http://hl7.org/fhir/StructureDefinition/condition-related]"
openEhrConfig:
  archetype: "openEHR-EHR-EVALUATION.problem_diagnosis.v1"
```
Context:
```
format: "0.2.0"

openEHR:
  templateId: "KDS_Diagnose"
  archetypes:
    - "openEHR-EHR-CLUSTER.anatomical_location.v1"
    - "openEHR-EHR-CLUSTER.lebensphase.v0"
    - "openEHR-EHR-CLUSTER.multiple_coding_icd10gm.v1"
    - "openEHR-EHR-EVALUATION.problem_diagnosis.v1"

fhir:
  resourceType: "Bundle"
  condition:
    targetRoot: "$fhirResource"
    targetAttribute: "entry.resource.meta.profile"
    operator: "one of"
    criteria: "[https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose]"
```
