### ISSUE TITLE
Date mappings 

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#20]
From FHIR to openEHR this is easy, but what if we have openEHR -> FHIR.
Here we need a logic to prioritze mappings, e.g. use dateTime and not period if possible.
I know the example is there cause of the workaround, but i can imagine that this will pop up again. 
In OMOCL I introduced alternatives for that, it will work down a [list](https://github.com/SevKohler/OMOCL/blob/536e9562e5c97cd66eb6b259692b4a672568192b/medical_data/instruction/Medication_statement_v0.yml#L16)
```YAML
      mappings:
        - name: "DateTime period" #workaround
          with:
            fhir: "onsetPeriod.start" # Period will be added, but currently is not supported in problem diangose
            #here we would like a not-exists condition if we wanted to pick between one, if both are provided (not here the case)
            openehr: "/data[at0001]/items[at0077]"
            type: "DATETIME" #interval, duratin etc is missing in FHIRConnect. 

        - name: "DateTime onset"
          with:
            fhir: "onsetDateTime" 
            openehr: "/data[at0001]/items[at0077]"
            type: "DATETIME"

```
