### ISSUE TITLE
Slots handling

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#21]
If the slots are anyways taking the $fhirResource always, we could load them directly and may not require any nesting. 
Yet, this maybe weird, just to record the idea:
```YAML
 - name: "body site"
    with:
      fhir: "$fhirResource.bodySite"
    followedBy:
      mappings:
        - name: "body site code"
          with:
            fhir: "coding"
            openehr: "/data[at0001]/items[at0012]" # Body site
            type: "CODING"
        - name: "body site text"
          with:
            fhir: "$fhirResource" #only forwarding the root, can this be done or does it lead to clashes with the father from above ? 
            #I guess the $ prevents that. 
            openehr: "/data[at0001]/items[openEHR-EHR-CLUSTER.anatomical_location.v1]"
          slotArchetype: "openEHR-EHR-CLUSTER.anatomical_location.v1"  
```
TO:
```YAML
openEhrConfig:
  archetype: "openEHR-EHR-EVALUATION.problem_diagnosis.v1"
  import: 
    - "openEHR-EHR-CLUSTER.anatomical_location.v1"
    
mappings:
  - name: "body site"
  with:
    fhir: "$fhirResource.bodySite"
  followedBy:
    mappings:
      - name: "body site code"
        with:
          fhir: "coding"
          openehr: "/data[at0001]/items[at0012]" # Body site
          type: "CODING" 
```
 
 Yet, we have to expect that the Cluster mapping may require other FHIR input too.
 
 Cluster mapping is:
```YAML
 format: "0.2.0"
version: "0.0.1"

openEhrConfig:
  archetype: "openEHR-EHR-CLUSTER.anatomical_location.v1"

mappings:
 - name: "body site"
    with:
      fhir: "$fhirResource.bodysite.code.text"  
      openehr: "/items[at0001]" #Name of body site
      type: "STRING"

```
