### ISSUE TITLE
Codings and term mappings  

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#22]
Templates of the KDS have only one coding now. 
The engine needs to add all other codings provided along in FHIR apart from the  required one to Term Mappings.

```YAML
        - name: "body site SCT code"
          with:
            fhir: "coding"
            openehr: "körperstelle_-_snomed-ct"
            type: "CODING"
          condition:
            targetRoot: "coding"
            targetAttribute: "system"
            operator: "one of"
            criteria: "[http://snomed.info/sct]"

        - name: "body site ICD 3 code"
          with:
            fhir: "coding"
            openehr: "körperstelle_-_icd-o-3"
            type: "CODING"
          condition:
            targetRoot: "coding"
            targetAttribute: "system"
            operator: "one of"
            criteria: "[http://terminology.hl7.org/CodeSystem/icd-o-3]"

```
Here the icd-0 will end up in a term mapping to the snomed code.
In FHIR we render them if not contained in the non-slices into the slices.
