### ISSUE TITLE
Ability for the engine to run AQLs as part of the mapping

### ISSUE THREAD

**Issue by gasperr** [medblocks/openFHIR#29]
Initially discussed here:
https://github.com/medblocks/openFHIR/issues/23

# References within mapping files
- when mapping (for example) context.encounter, we need to be able to trigger an AQL to find an Encounter that was already mapped (in the past). Unless of course it's provided as an incoming data to the openFHIR.
- we ignore business (External) identifier (we don't try to resolve those)

**Grammar**:
```
  - name: "encounter reference"
    with:
      fhir: "$fhirResource.encounter"
      openehr: "$openEhrArchetype.fall_kennung" 
      type: "AQL"    # a new type defined, this lets the engine know it needs to trigger an AQL against the integrated openEHR CDR
      aql: "write the actual aql with 'fhir' in there in the aql" # %fhir% is a placeholder that the engine replaces with what it extracts from the fhir path (fhirResource.encounter)
```
**Example**:
```
  - name: "encounter reference"
    with:
      fhir: "$fhirResource.encounter"
      openehr: "$openEhrArchetype.fall_kennung" 
      type: "AQL"
      aql: "SELECT c/uid/value FROM COMPOSITION c ...... WHERE c/archetype_details/a.. ='%fhir%' "
```

**Interpretation**:
- when mapping from FHIR to openEHR, engine will (1) extract FHIR path value (fhirResource.encounter) and trigger an AQL against the integrated CDR (after replacing placeholder %fhir%), for example `SELECT c/uid/value FROM COMPOSITION c ...... WHERE c/archetype_details/a.. ='Encounter/123123')`
- aql result will be added to the constructing openEHR Composition ($openEhrArchetype.fall_kennung)
- when mapping from openEHR to FHIR, whatever is in the openEhrArchetype.fall_kennung will be, as such, placed on fhirResource.encounter (optionally the actual reference as it was once obtained can be placed here, if engine stores rewritten references)
