### ISSUE TITLE
OMOCL integration

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#3]
Sidharth:
I believe the future we're looking at is a specification/engine that maps openEHR to other formats bidirectionally. So openEHR being on one side of the mapping is always implied. Correct?

Unless any of you @gasperr, @SevKohler think this project has scope beyond just openEHR mappings?

E.g.: OMOP to FHIR? or FHIR to OMOP?

(My opinion is that we build the spec, and the engine just around openEHR for now.)

If one side is always implied, and we just need to separate the mapping files into these:
- Metadata about the mapping (like name, version etc.)
- Engine specification (what engine? What version?)
- Mapping specification (the specific bidirectional mapping language)

This way, we don't technically need to evolve the "FHIRConnect" spec, but we just use the FHIRConnect spec's JSON Schema in one of the fields (`spec`).

Taking a page out of the [Kubernetes YAML spec](https://kubernetes.io/docs/concepts/overview/working-with-objects/):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

we could do something like:

```yaml
engine: FHIRConnect/v0.0.1
kind: Model / Context
metadata:
  name: some-mapping-name
  version: 0.0.1a # version of this particular mapping
spec: # schema specific to the FHIRConnect v0.0.1 engine
   system: FHIR
   version: R4
   openEhrConfig:
     archetype: "openEHR-EHR-INSTRUCTION.medication_order.v2"
```

And something for OMOCL would look something like

```yaml
engine: OMOCL/v0.0.1
kind: Model
metadata:
  name: some-mapping-name
  version: 0.0.1a # version of this particular mapping
spec: # schema specific to the OMOCL v0.0.1 engine
   system: CDM
   version: v5.4
   openEhrConfig:
     archetype: "openEHR-EHR-INSTRUCTION.medication_order.v2"
```

One advantage could be that the different mapping languages and specifications could evolve independently of the "openFHIR schema". Another is that, we don't need file names / folder structures to imply what's a model file vs context file - all the details are in the file itself.

But again, this may not be something we want, and we might be **overabstracting** too early. Either way, I'm happy with any decision made here. 

@SevKohler what would the feasibility of integration of all the work you're doing with OMOCL into openFHIR be? Maybe should be continued in another thread.

_Originally posted by @sidharthramesh in https://github.com/medblocks/openFHIR/issues/2#issuecomment-2406740994_
