### ISSUE TITLE
Different mappings EVENT.time Laboratory

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#31]
If a lab has in FHIR 2 analytes with two different measurement times, there is the need to create two events in the laboratory_result observation, since the event_time represents the measurement_time of the panel done. 
Example
FHIR
1
dateTime 1200
specimen Blood
Result 12 mg

2
dateTime 1200
specimen Blood
Result 13 mg

3
dateTime 1300
specimen Blood
Result 15 mg

In openEHR this would be:
1 event 1200
blood
2x 13mg and 12mg

1x event 1300
blood
1x 15mg

We defined the following logic for that, first the mapping will create 3 events and if the rootPath excluding the point of merge is the same, merge the analytes into one event. 

```YAML
post_processor:
    - name: "mergeAnalytes" 
    type: "merge"                           
    target: openEHR # no support for FHIR needed in this project
    rootPath: /content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001] 
    merge_on:
    	openEHR-EHR-CLUSTER.laboratory_test_analyte.v1
# this will create a hash from everything from rootPath on, excluding the to merge archetype
# If several events exist just delete duplicates and write the analyte into one of them
```
