### ISSUE TITLE
static type: types vs dynamic types

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#37]
Currently we define each type of the mapping. 
I think this should be done by the engine. 
Often we have the case e.g. coding -> text or even valueCoding to quantity etc. 
Its mostly the same actions, if we have static types we have to write mappings manually for these types e.g.:
``` YAML
mappings:
  - name: "bodySiteText"
    with:
      fhir: "$fhirResource.bodysite.text"
      openehr: "$openEhrArchetype/items[at0001]" #Name of body site
      type: "STRING"
    condition:
      targetRoot: "$fhirResource.bodysite"
      targetAttribute: "coding"
      operator: "empty"

  - name: "bodySiteCoded"
    with:
      fhir: "$fhirResource.bodysite"
      openehr: "$openEhrArchetype/items[at0001]" #Name of body site
      type: "CODEABLECONCEPT"
    condition:
      targetRoot: "$openEhrArchetype"
      targetAttribute: "/items[at0001]"
      operator: "type"
      criteria: ["DV_CODED_TEXT"]
```
I have to introduce two new operators for this to work, which i think the engine should do. 
Downside, we have to be aware what the types in the FHIRresource and Template are and infere the mappings from there on. 
If we just plug json paths together that information has to be retrieved from the opt, structureDef. 

``` YAML
mappings:
  - name: "bodySiteText"
    with:
      fhir: "$fhirResource.bodysite.text"
      openehr: "$openEhrArchetype/items[at0001]" #Name of body site

  - name: "bodySiteCoded"
    with:
      fhir: "$fhirResource.bodysite"
      openehr: "$openEhrArchetype/items[at0001]" #Name of body site

```
Here the code will check the types and execute the mappings accordingly, this is also what we did in OMOCL and partly in the  old FHIRBridge. 

I think in general we really should do this cause it will safe us tremendous amounts of work + make the mappings much more maintainable.
