### ISSUE TITLE
Bundle clause in the context

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#38]
I dont think we need this (everywhere) i think the profile should be registered as part of the mapping.
So we have auto resolves for references and profiles. 
E.g. check reference, if its there, execute mapping (e.g.new composition) if the Bundle is chaotic. 

``` YAML
  resourceType: "Bundle"
  condition:
    target: "$fhirResource.entry.resource.meta.profile"
    operator: "one of"
    criteria: "[https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose]"
```

This should be contained in the header of mappings:

```YAML
  fhirConfig:
    fhirProfile: https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose

```
This would also make the vanilla mappings executable if we get no profile and just a vanilla.
