### ISSUE TITLE
adding logic of manual mapping

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#40]
```YAML
  - name: "referenzPrimaerdiagnose"
    extension: "add"
    with:
      fhir: "$fhirResource.extension"
      openehr: "$openEhrArchetype/at0063"
      type: "MANUAL"
      manual:
        openEHR:
          path: "/at0063" # the terminology should be set automatically
          type: "DV_CODED_TEXT"
          value:
            code_string: "at0064"
            terminology_id: "local"
            value: "Hauptdiagnose"
          condition:
            targetRoot: "extension"
            targetAttribute: "url"
            operator: "not of"
            criteria: "[http://hl7.org/fhir/StructureDefinition/condition-related]"


  - name: "referenzNebendiagnose" #should maybe be contained under the referenzPrimaer
    extension: "add"
    with:
      fhir: "$fhirResource"
      openehr: "$openEhrArchetype"
      type: "MANUAL"
      manual:
        openehr:
          path: "/at0063"
          type: "DV_CODED_TEXT"
          value:
            code_string: "at0066"
            terminology_id: "local"
            value: "Nebendiagnose"
          condition:
            targetRoot: "extension"
            targetAttribute: "url"
            operator: "one of"
            criteria: "[http://hl7.org/fhir/StructureDefinition/condition-related]"
        fhir:
          path: "$fhirResource.extension.url"
          value: "http://hl7.org/fhir/StructureDefinition/condition-related" #linkage happens in the postprocessor
          condition:
            targetRoot: "/at0063"
            targetAttribute: "/defining_code/code_string"
            operator: "one of"
            criteria: "at0066"

```
This is required in order to map primary and secondary diagnose correctly. 
Values should be derived from the openEHR and FHIR model. 
Only support the ones we need for the KDS   to minimize effort (DV_CODED) .
Rest we can add in the future.
