### ISSUE TITLE
Reference from openEHR -> FHIR link

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#46]
1. If there is a reference called in openEHR and a mapping is there for this reference, this mapping is to be executed. 
So in this case not only the identifier is to be processed but ALL of the resource. 
Otherwise the output would differ from what was intially provided. 
2. The link to this composition is to be maintained in the link of the locatable therefore it is back provideable as a reference or even whole resource.
Also in this case its several resources types supported for this reference therefore dynamic typing is required. 

Problem basedOn is of several resourceType types. 
```YAML
   - name: "basedOn"
    extension: "add"
    with:
      fhir: "$fhirResource.basedOn"
      openehr: "$reference"
      type: "NONE"
    reference:
      mappings:
        - name: "identifierInReference"
          with:
            fhir: "$fhirRoot.identifier.value"
            openehr: "$openehrArchetype/protocol[at0004]/items[at0094]/items[at0063]"
            type: "IDENTIFIER"
        - name: "cascadeMapping"
          with:
            fhir: "$fhirRoot"
            openehr: "$openehrArchetype/protocol[at0004]/items[at0094]/items[at0063]" # will use link
            type: "REFERENCED_MAPPING" # execute mapping or use already mapped one to get Composition URI
            openehr_link:
              meaning: "the identifier which it derived from"
              type: "based on"
```
