### ISSUE TITLE
bundle logic for meta profile as standard logic 

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#47]
```YAML
  resourceType: "Bundle"
  condition:
    target: "$fhirResource.entry.resource.meta.profile"
    operator: "one of"
    criteria: "[https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose]"
```

to:
```YAML
context:
  profileUrl: "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose"
  templateId: "KDS_Diagnose"
  archetypes:
    - "openEHR-EHR-CLUSTER.multiple_coding_icd10gm.v1" # i dont think we need to list clusters here ?
    - "openEHR-EHR-EVALUATION.problem_diagnosis.v1"
    - "openEHR-EHR-CLUSTER.problem_qualifier.v2"
    - "openEHR-EHR-CLUSTER.lebensphase.v0"
    - "openEHR-EHR-CLUSTER.case_identification.v0"
  extensions:
    - "KDSProblemDiagnosis" #they overload the vanilla mappings, no version = take the latest
    - "KDSProblemQualifier"
    - "KDSLebensphase"

```
This will help resolving references back from openEHR to FHIR, since mappings need to recreate FHIR.
