### ISSUE TITLE
Two conditions required. 

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#48]
```YAML
  - name: "primärdiagnose"
    extension: "add"
    with:
      fhir: "$resource.extension"
      openehr: "$archetype"
      type: "NONE"
    condition:
      targetRoot: "$resource.extension"
      targetAttribute: "url"
      operator: "one of"
      criteria: "[http://hl7.org/fhir/StructureDefinition/condition-related]"
    followedBy:
      mappings:
        - name: "referencedCondition"
          with:
            fhir: "$fhirRoot.value"
            openehr: "$archetype"
          reference:
            resourceType: "Condition"
            mappings:
              - name: "primary"
                with:
                  fhir: "$fhirRoot"
                  openehr: "$archetype"
                slotArchetype: "EVALUATION.problem_diagnosis.v1"
          condition:
            targetRoot: "/data[at0001]/items[openEHR-EHR-CLUSTER.problem_qualifier.v2]"
            targetAttribute: "/items[at0063]/defining_code/code_string"
            operator: "one of"
            criteria: "[at0064]"
```
Just encoiuntered this while correcting the mappings, here we need actually two conditions, i had the luxury to have different layers, but there might be the case where you got one openehrCondition and one fhirCondition. 
Maybe we either split it or leave it be and say well you can always add an followedBy.
