### ISSUE TITLE
Conditin and paths in general

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#73]
```YAML
  - name: "date"
    extension: "add"
    with:
      fhir: "$resource"
      openehr: "$archetype"
      type: "NONE"
    fhirCondition:
      targetRoot: "$resource.extension"
      targetAttribute: "url"
      operator: "one of"
      criteria: "[http://hl7.org/fhir/StructureDefinition/condition-assertedDate]"
    openehrCondition:
      targetRoot: "$archetype/data[at0001]"
      targetAttribute: "/items[at0003]"
      operator: "not empty" # added so i dont have to followedBy to festellungsdatum
    followedBy:
      mappings:
        - name: "feststellungsdatum"
          with:
            fhir: "value.as(DateTimeType)"
            openehr: "/data[at0001]/items[at0003]"
        - name: "staticExtensionUrl"  # should be followeBy of festellungsdatum
          with:
            fhir: "$fhirRoot"
            openehr: "$reference"
          manual:
            - name: "url"
              fhir:
                path: "url"
                value:
                  url: "http://hl7.org/fhir/StructureDefinition/condition-assertedDate"


```

i still think the way we use paths is really weird i think, here i cant call staticExtensionUrl as part of festellungsdatum, it should be there attached to the followedBy.
Yet this wont work, since i would point to a extension , how should the engine know i mean the one at the begining of the path ?
The engine wouldnt know which one to take.               

I worked around that by checking for not empty.

In general i think also that condition should always be on the path of the with UNLESS it stated otherwise ?!
Imagine there are two extension i want to access to on that is NOT in the with, currently that wont work,
