### ISSUE TITLE
How do we handle clusters that are not in a template

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#74]
Hey, 

i often have the case where i have a cluster mapping that is not hard backed in the archetype. 
Currently i have this in the extension mapping, yet i think in 99% of the cases of a mapping this may exactly that cluster in a templates. 
e.g. 
```YAML
  - name: "clinicalStatus"
    extension: "add"
    with:
      fhir: "$resource"
      openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.problem_qualifier.v2]"
    slotArchetype: "CLUSTER.problem_qualifier.v2"
```
This mapping maps clinical status, yet the cluster problem qualifier is in the template, so i moved it to the extension mapping.
I think this is the correcty way FIRST, yet now i think it should be in the model and if people are not using that cluster in THEIR template they can overwrite it (with NONE or their way of doing clinicalStatus).
This would provide a defacto mapping also aligning the governance of how to map it, which could be reworked. 

Im not sure about this since this would also be a modeling recommendation.
