### ISSUE TITLE
linking demographics resources

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#76]
In general all the links we do to the demographics will contain identifier (composer, partitioner etc. ), for a mapping back it would be nice in the future that the openFHIR pulls the fields then also from a FHIR server instead of merely giving back the identifier.

```YAML
  - name: "composer"
    with:
      fhir: "$resource.requester"
      openehr: "$composition/composer" #take the first one if its 0..n ?!
```
