### ISSUE TITLE
Rename of model files ?

### ISSUE THREAD

**Issue by SevKohler** [medblocks/openFHIR#77]
Since model mappings always have a fhirinput -> openEHR archetype. 
The FHIR input can differ, sometimes you have a BackBoneElement -> archetype and sometimes something else. 
I think we should add the name of WHAT fhir input this maps to the model files, to make it easier and clearer what is mapped. 
Currently, im adding the strucutureDefinition, these do not have impact on the mappings and should be seen more as a documentation. 
THERE could be a clash where you map another StructureDefinition which has the same paths (status ...) but i think this is super unlikely, in that case you can also create a new file.
```YAML
engine: FHIRConnect/v0.0.1
type: model
metadata:
  name: INSTRUCTION.service_request.v1
  version: 0.0.1a
spec:
  system: FHIR
  version: R4
  openEhrConfig:
    archetype: openEHR-EHR-INSTRUCTION.service_request.v1
  fhirConfig:
    structureDefinition: http://hl7.org/fhir/StructureDefinition/ServiceRequest
```
Here it maybe good to add in general the fhirInput to the names of the model files e.g.:
- service_request.v1.service_request
- dosage.v2.BackboneElement
- dosage.v2.dosage

Where the last name is what fhir type was mapped. 
Currently, i have on file, if i have to add another one i just add to BOTH the fhirInput.
- dosage.v2.BackboneElement
- dosage.v2.dosage
This has the downside that people would need to change their slot everywhere. 
So there is two ways now:
1. Add the fhirInput always to the name of the mapping + filename. 
2. Have one default and the rest has to add their fhirInput e.g.:
- dosage.v2.BackboneElement
- dosage.v2 (default since it maps dosage->dosage)
